import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as XLSX from '../app/vendor/xlsx.mjs';
import { parseSalesforceSummary, reconcileMonth, reconcileYear } from '../app/js/sf/salesforce.js';

// Shaped like the "Opportunity Proof of Cash" report: starts at B2, a month label on its first row.
function report() {
  const aoa = [
    ['Opportunity Proof of Cash 2024'], ['As of 2026-09-27 18:27:21 Pacific Standard Time/PST • Generated by A'], [], [], ['Filtered By'],
    ['Date Field: Close Date equals Current FY (10/1/2025 to 9/30/2026)'], ['Opportunity Record Type not equal to Purchase'], [],
    ['Close Date  ↑', 'Payment Method  ↑', 'Sum of Amount', 'Record Count'],
    ['December 2025', 'Stripe', '$4,185,562.13', '30673'], [null, 'Wire', '$1,148,525.21', '1992'], [null, 'Check', '$1,000.00', '2'],
    ['January 2026', '', '$4.23', '1'], [null, 'Stripe', '$1,719,209.51', '28512'],
    ['Total', null, '$7,054,301.08', '61180'],
  ];
  const ws = XLSX.utils.aoa_to_sheet(aoa, { origin: 'B2' });
  const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, 'r');
  return wb;
}

test('the Salesforce summary report reads by month and payment method', () => {
  const r = parseSalesforceSummary(XLSX, report());
  assert.equal(r.asOf, '2026-09-27');
  assert.deepEqual(r.months.map((m) => [m.month, m.total]), [['2025-12', 5335087.34], ['2026-01', 1719213.74]]);
  assert.deepEqual(r.months[0].methods.Wire, { amount: 1148525.21, count: 1992 });
  assert.equal(r.months[1].methods['(none)'].amount, 4.23);
});

test('Salesforce vs GL: refunds and disputes explain Stripe; a big line under the wrong payer is flagged', () => {
  const r = reconcileMonth({
    sf: { month: '2026-02', methods: { Stripe: { amount: 1641299.31, count: 1 }, Patreon: { amount: 2285.08, count: 1 } } },
    giving: { channels: { Stripe: 1620320.76, Patreon: 100478.47 }, stripe: { 'Refunds CC Gross Amount': -17501, 'Wire Refunds Gross Amount': -1700, 'Dispute Gross Amount': -35 },
      big: { Patreon: [{ batch: 'GL017631', payer: 'Patreon', amount: 100478.47 }] } },
  });
  const stripe = r.rows.find((x) => x.channel === 'Stripe');
  assert.equal(stripe.explained, 19236);
  assert.equal(stripe.unexplained, 1742.55);
  assert.ok(r.reasons.some((x) => x.flag && /Patreon/.test(x.what) && /GL017631/.test(x.why)));
});

test('month-end timing: what one month leaves in a channel and the next month cancels', () => {
  const [dec, jan] = reconcileYear([
    { sf: { month: '2025-12', methods: { Stripe: { amount: 4185562.13 } } }, giving: { channels: { Stripe: 3871839.86 } } },
    { sf: { month: '2026-01', methods: { Stripe: { amount: 1719209.51 } } }, giving: { channels: { Stripe: 2010150.82 } } },
  ]);
  assert.ok(dec.reasons.some((x) => /Month-end timing/.test(x.what)));
  assert.equal(dec.unexplained, 0);
  assert.equal(jan.unexplained, 0);
});

test('money received now for revenue the GL recognized earlier explains Salesforce being higher', () => {
  const r = reconcileMonth({
    sf: { month: '2026-03', methods: { Wire: { amount: 1003467.44 } } }, giving: { channels: { Wire: 219860.55 } },
    found: { priorPeriod: [{ channel: 'Wire', amount: 750595, desc: 'M.J. Murdock grant', source: 'GL 1220' }] },
  });
  assert.equal(r.rows[0].explained, 750595);
  assert.equal(r.unexplained, 33011.89);
});
