import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as XLSX from '../app/vendor/xlsx.mjs';
import { parseSalesforceSummary, parseSalesforceReport, coveredMonths, reportExcludes, reconcileMonth, reconcileYear } from '../app/js/sf/salesforce.js';

// Shaped like the "Opportunity Proof of Cash" report: starts at B2, a month label on its first row.
function report() {
  const aoa = [
    ['Opportunity Proof of Cash 2024'], ['As of 2026-09-27 18:27:21 Pacific Standard Time/PST • Generated by A'], [], [], ['Filtered By'],
    ['Date Field: Close Date equals Current FY (10/1/2025 to 9/30/2026)'], ['Opportunity Record Type not equal to Purchase'], [],
    ['Close Date  ↑', 'Payment Method  ↑', 'Sum of Amount', 'Record Count'],
    ['December 2025', 'Stripe', '$4,185,562.13', '30673'], [null, 'Wire', '$1,148,525.21', '1992'], [null, 'Check', '$1,000.00', '2'],
    ['January 2026', '', '$4.23', '1'], [null, 'Stripe', '$1,719,209.51', '28512'],
    ['Total', null, '$7,054,301.08', '61180'],
  ];
  const ws = XLSX.utils.aoa_to_sheet(aoa, { origin: 'B2' });
  const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, 'r');
  return wb;
}

test('the Salesforce summary report reads by month and payment method', () => {
  const r = parseSalesforceSummary(XLSX, report());
  assert.equal(r.asOf, '2026-09-27');
  assert.deepEqual(r.months.map((m) => [m.month, m.total]), [['2025-12', 5335087.34], ['2026-01', 1719213.74]]);
  assert.deepEqual(r.months[0].methods.Wire, { amount: 1148525.21, count: 1992 });
  assert.equal(r.months[1].methods['(none)'].amount, 4.23);
});

test('Salesforce vs GL: refunds and disputes explain Stripe; a big line under the wrong payer is flagged', () => {
  const r = reconcileMonth({
    sf: { month: '2026-02', methods: { Stripe: { amount: 1641299.31, count: 1 }, Patreon: { amount: 2285.08, count: 1 } } },
    giving: { channels: { Stripe: 1620320.76, Patreon: 100478.47 }, stripe: { 'Refunds CC Gross Amount': -17501, 'Wire Refunds Gross Amount': -1700, 'Dispute Gross Amount': -35 },
      big: { Patreon: [{ batch: 'GL017631', payer: 'Patreon', amount: 100478.47 }] } },
  });
  const stripe = r.rows.find((x) => x.channel === 'Stripe');
  assert.equal(stripe.explained, 19236);
  assert.equal(stripe.unexplained, 1742.55);
  assert.ok(r.reasons.some((x) => x.flag && /Patreon/.test(x.what) && /GL017631/.test(x.why)));
});

test('month-end timing: what one month leaves in a channel and the next month cancels', () => {
  const [dec, jan] = reconcileYear([
    { sf: { month: '2025-12', methods: { Stripe: { amount: 4185562.13 } } }, giving: { channels: { Stripe: 3871839.86 } } },
    { sf: { month: '2026-01', methods: { Stripe: { amount: 1719209.51 } } }, giving: { channels: { Stripe: 2010150.82 } } },
  ]);
  assert.ok(dec.reasons.some((x) => /Month-end timing/.test(x.what)));
  assert.equal(dec.unexplained, 0);
  assert.equal(jan.unexplained, 0);
});

test('money received now for revenue the GL recognized earlier explains Salesforce being higher', () => {
  const r = reconcileMonth({
    sf: { month: '2026-03', methods: { Wire: { amount: 1003467.44 } } }, giving: { channels: { Wire: 219860.55 } },
    found: { priorPeriod: [{ channel: 'Wire', amount: 750595, desc: 'M.J. Murdock grant', source: 'GL 1220' }] },
  });
  assert.equal(r.rows[0].explained, 750595);
  assert.equal(r.unexplained, 33011.89);
});

// Shaped like the gift-level "Opportunity … Account and tranxn" export (anonymized): starts at B2,
// filters above the header, one row per gift, a Total line and a footer.
function gifts(range = '10/1/2025 to 12/31/2025', rows = null) {
  const aoa = [
    [null, 'Opportunity 2025 Account and tranxn'], [null, 'As of 2026-09-28 15:10:07 Pacific Standard Time/PST • Generated by A • Sorted by Amount (Descending)'], [], [], [null, 'Filtered By'],
    [null, `Date Field: Close Date equals Custom (${range})`], [null, 'Show: All opportunities'], [null, 'Opportunity Record Type not equal to Purchase'],
    [null, 'Stripe Transaction Status not equal to Disputed,Refunded,Processing,Failed,Refund Created,Refund Failed'], [null, 'Stage equals Posted'], [],
    [null, 'Amount', 'Close Date', 'Credit Card Transaction Id Raw', 'Credit Card Transaction Id', 'Stage', '18 Char ID Primary Contact', 'Donor-Advised', 'Payment Method'],
    ...(rows || [
      ['$150,000.00', '12/4/2025', '', '', 'Posted', '003A', 'A Charitable Fund', 'Check'],
      ['$100,000.00', '10/31/2025', '', '', 'Posted', '003B', 'Fidelity', 'Wire'],
      ['$70,000.00', '12/17/2025', 'py_1', 'py_1-donation', 'Posted', '003C', '', 'Stripe'],
      ['$25.00', '12/17/2025', 'py_2', 'py_2-donation', 'Posted', '003D', '', 'Stripe'],
      ['-$13.20', '10/3/2025', '', '', 'Posted', '003E', 'Stewardship', 'Wire'],
    ]).map((r) => [null, ...r]),
    ['Total', 'Sum', '$220,011.80'], [null, 'Count', '5'], [], [null, null, 'Confidential Information - Do Not Distribute'],
  ];
  const ws = XLSX.utils.aoa_to_sheet(aoa, { origin: 'B2' });
  const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, 'r');
  return wb;
}

test('the gift-level report is totalled by month and payment method, check and wire gifts kept', () => {
  const r = parseSalesforceReport(XLSX, gifts());
  assert.equal(r.kind, 'gifts');
  assert.equal(r.asOf, '2026-09-28');
  // November has no gifts in the file, but the report covers it: saved as none.
  assert.deepEqual(r.months.map((m) => [m.month, m.total, m.count]), [['2025-10', 99986.8, 2], ['2025-11', 0, 0], ['2025-12', 220025, 3]]);
  assert.deepEqual(r.months[2].methods.Stripe, { amount: 70025, count: 2 });
  assert.deepEqual(r.months[2].gifts, [['2025-12-04', 150000, 'A Charitable Fund', '003A', 'C']]);
  assert.deepEqual(r.months[0].gifts.map((g) => g[1]), [100000, -13.2]);
  assert.deepEqual(r.excludes, { refunds: true, disputes: true });
});

test('the months a report covers come from its date filter', () => {
  assert.deepEqual(coveredMonths(['Date Field: Close Date equals Custom (10/1/2025 to 12/31/2025)']).months, ['2025-10', '2025-11', '2025-12']);
  // Part of a month: covered, and said so.
  assert.deepEqual(coveredMonths(['Date Field: Close Date equals Custom (10/15/2025 to 11/30/2025)']).partial, ['2025-10']);
  // A whole-year filter covers only the months up to when the report was run.
  assert.deepEqual(coveredMonths(['Date Field: Close Date equals Current FY (10/1/2025 to 9/30/2026)'], '2026-01-20').months, ['2025-10', '2025-11', '2025-12', '2026-01']);
  assert.equal(coveredMonths(['Date Field: Close Date equals Last Quarter']), null);
  assert.deepEqual(reportExcludes(['Opportunity Record Type not equal to Purchase']), { refunds: false, disputes: false });
});

test('the summary report still reads, and its date filter says which months it covers', () => {
  const r = parseSalesforceReport(XLSX, report());
  assert.equal(r.kind, 'summary');
  assert.deepEqual(r.months.map((m) => m.month), ['2025-10', '2025-11', '2025-12', '2026-01', '2026-02', '2026-03', '2026-04', '2026-05', '2026-06', '2026-07', '2026-08', '2026-09']);
  assert.equal(r.months.find((m) => m.month === '2025-12').total, 5335087.34);
});

test('when the report already leaves out refunded and disputed gifts, the GL’s refunds explain nothing', () => {
  const giving = { channels: { Stripe: 1620320.76 }, stripe: { 'Refunds CC Gross Amount': -17501, 'Dispute Gross Amount': -35 } };
  const kept = reconcileMonth({ sf: { month: '2026-02', methods: { Stripe: { amount: 1641299.31 } } }, giving });
  const left = reconcileMonth({ sf: { month: '2026-02', methods: { Stripe: { amount: 1641299.31 } }, excludes: { refunds: true, disputes: true } }, giving });
  assert.equal(kept.explained, 17536);
  assert.equal(left.explained, 0);
});
